#------------本地读取配置-------------------
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
#  application:
#    name: config-server
server:
  port: 8768
#------------Git仓库读取配置-------------------
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DorraChen/springcloudconfig
          search-paths: respo
          username: *****
          password: *****
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
